### ISSUE TITLE
Hardcoded thread count can be sub-optimal.

### ISSUE THREAD

**Issue by pipatron** [brndd/music-convert.sh#1]
AFAIK GNU Parallel auto-detects some sort of optimum thread count if nothing is given, but you always give it a number by default, and that can be sub-optimal.

I suggest to only give it the `-j` flag if set by the caller, otherwise leave it blank. Another option would be to investigate constructs such as `-j 100%` etc.

**Comment by brndd** [comment]
parallel defaults to the number of logical cores rather than the number of physical cores, so I did the sane thing and made the script default to the number of physical cores on my NAS ;)

**Comment by brndd** [comment]
Fixed by [c90bedb](https://github.com/brndd/music-convert.sh/commit/c90bedbc0810db9668791fde317b6eb92a39c989) ;)
